Repository hit-it-PDA/BE, pull requests merged in 2024-06, with the labels that each got.

#6 #5 hotfix: globalexceptionhandler 처리 못하는 이슈 해결
  user-service/src/main/java/com/pda/user_service/UserServiceApplication.java
Labels: 🐛 bug/error

#7 #1 feat: (WIP) 유저 로그인 회원가입 기능 개발
  .gitignore
  build.gradle
  user-service/src/main/java/com/pda/security/JwtAuthenticationFilter.java
  user-service/src/main/java/com/pda/security/JwtTokenProvider.java
  user-service/src/main/java/com/pda/security/WebSecurityConfig.java
  user-service/src/main/java/com/pda/user_service/controller/UserController.java
  user-service/src/main/java/com/pda/user_service/dto/KaKaoTokenDto.java
  user-service/src/main/java/com/pda/user_service/dto/KakaoUserDto.java
  user-service/src/main/java/com/pda/user_service/dto/LoginDto.java
  user-service/src/main/java/com/pda/user_service/dto/LoginResponseDto.java
  user-service/src/main/java/com/pda/user_service/dto/UserDto.java
  user-service/src/main/java/com/pda/user_service/jpa/User.java
  user-service/src/main/java/com/pda/user_service/jpa/UserRepository.java
  user-service/src/main/java/com/pda/user_service/service/UserService.java
  utils/src/main/java/com/pda/utils/api_utils/StringUtils.java
  utils/src/main/java/com/pda/utils/exception/GlobalExceptionHandler.java
  utils/src/main/java/com/pda/utils/exception/InvalidParameterException.java
  utils/src/main/java/com/pda/utils/exception/login/NotCorrectPasswordException.java
  utils/src/main/java/com/pda/utils/exception/login/NotFoundUserException.java
  utils/src/test/java/com/pda/utils/api_utils/StringUtilsTest.java
Labels: ✨ feature

#11 fix: 수정된 테이블명 매핑
  user-service/src/main/java/com/pda/user_service/jpa/User.java
Labels: 🐛 bug/error

#16 fix: cors 적용
  user-service/src/main/java/com/pda/security/WebSecurityConfig.java
Labels: 🐛 bug/error

#18 feat: (WIP) 카카오톡 회원가입 로그인 기능 개발
  user-service/src/main/java/com/pda/user_service/controller/UserController.java
  user-service/src/main/java/com/pda/user_service/dto/KakaoUserDto.java
  utils/src/main/java/com/pda/utils/api_utils/StringUtils.java
  utils/src/test/java/com/pda/utils/api_utils/StringUtilsTest.java
Labels: ✨ feature

#23 #22 feat: jwt에 user_id 담아서 보내기
  user-service/src/main/java/com/pda/security/WebSecurityConfig.java
  user-service/src/main/java/com/pda/user_service/controller/UserController.java
  user-service/src/main/java/com/pda/user_service/jpa/User.java
  user-service/src/main/java/com/pda/user_service/service/UserService.java
  utils/src/main/java/com/pda/utils/exception/GlobalExceptionHandler.java
Labels: ✨ feature

#26 fix: Security 인가 설정 변경 & jwt 토큰 읽기
  user-service/src/main/java/com/pda/investment_test/controller/InvestmentTestController.java
  user-service/src/main/java/com/pda/security/JwtAuthenticationFilter.java
  user-service/src/main/java/com/pda/security/JwtTokenProvider.java
  user-service/src/main/java/com/pda/security/WebSecurityConfig.java
  user-service/src/main/java/com/pda/user_service/service/UserService.java
Labels: duplicate

#28 #10 feat: 투자성향테스트 질문 id로 조회 API 추가
  user-service/src/main/java/com/pda/UserServiceApplication.java
  user-service/src/main/java/com/pda/investment_test/controller/InvestmentTestController.java
  user-service/src/main/java/com/pda/investment_test/dto/QuestionAndAnswerDto.java
  user-service/src/main/java/com/pda/investment_test/jpa/answer/Answer.java
  user-service/src/main/java/com/pda/investment_test/jpa/answer/AnswerRepository.java
  user-service/src/main/java/com/pda/investment_test/jpa/question/Question.java
  user-service/src/main/java/com/pda/investment_test/jpa/question/QuestionRepository.java
  user-service/src/main/java/com/pda/investment_test/service/InvestmentTestService.java
  user-service/src/main/java/com/pda/security/WebSecurityConfig.java
  user-service/src/test/java/com/pda/user_service/RDSTest/RDSConnectionTest.java
  utils/src/main/java/com/pda/utils/exception/GlobalExceptionHandler.java
  utils/src/main/java/com/pda/utils/exception/investment_tests/NotFoundQuestionException.java
Labels: ✨ feature

#31 #30 hotfix: enablejparepositories 에러 해결
  portfolio-service/src/main/java/com/pda/portfolio_service/PortfolioServiceApplication.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioRepository.java
  user-service/src/main/java/com/pda/UserServiceApplication.java
  user-service/src/main/java/com/pda/investment_test/jpa/answer/AnswerRepository.java
  user-service/src/main/java/com/pda/investment_test/jpa/question/QuestionRepository.java
  user-service/src/main/java/com/pda/user_service/jpa/UserRepository.java
Labels: 🐛 bug/error

#32 #29 feat: 자체 서비스 포트폴리오 펀드 상세 조회
  portfolio-service/src/main/java/com/pda/portfolio_service/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/HititPortfoliosFundsResponseDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/HititPortfoliosResponseDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/HititPortfoliosFundProductId.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioFund.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioFundRepository.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioRepository.java
  portfolio-service/src/main/java/com/pda/portfolio_service/service/PortfolioService.java
Labels: ✨ feature

#34 #33 feat: 포트폴리오 수익률 연산 구현
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/HititPortfoliosFundsResponseDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/HititPortfoliosResponseDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/service/PortfolioService.java
Labels: ✨ feature

#36 #10 feat: 투자 성향 테스트 기능 개발
  user-service/src/main/java/com/pda/investment_test/controller/InvestmentTestController.java
  user-service/src/main/java/com/pda/investment_test/dto/QuestionDto.java
  user-service/src/main/java/com/pda/investment_test/dto/ResultDto.java
  user-service/src/main/java/com/pda/investment_test/jpa/InvestmentType.java
  user-service/src/main/java/com/pda/investment_test/jpa/answer/AnswerRepository.java
  user-service/src/main/java/com/pda/investment_test/jpa/user_answer/UserAnswer.java
  user-service/src/main/java/com/pda/investment_test/jpa/user_answer/UserAnswerRepository.java
  user-service/src/main/java/com/pda/investment_test/service/InvestmentTestService.java
  user-service/src/main/java/com/pda/security/JwtTokenProvider.java
  user-service/src/main/java/com/pda/user_service/dto/KakaoUserDto.java
  user-service/src/main/java/com/pda/user_service/dto/SignupUserDto.java
  user-service/src/main/java/com/pda/user_service/dto/UserInfoDto.java
  user-service/src/main/java/com/pda/user_service/jpa/User.java
  user-service/src/main/java/com/pda/user_service/service/UserService.java
  utils/src/main/java/com/pda/utils/api_utils/CustomStringUtils.java
  utils/src/main/java/com/pda/utils/api_utils/StringListConverter.java
  utils/src/main/java/com/pda/utils/exception/GlobalExceptionHandler.java
  utils/src/main/java/com/pda/utils/exception/investment_tests/AnswerNotFoundException.java
  utils/src/main/java/com/pda/utils/exception/investment_tests/QuestionNotFoundException.java
  utils/src/main/java/com/pda/utils/exception/investment_tests/UserAnswerNotFoundException.java
  utils/src/test/java/com/pda/utils/api_utils/CustomStringUtilsTest.java
  utils/src/test/java/com/pda/utils/api_utils/StringUtilsTest.java
Labels: ✨ feature

#39 #35 feat: 자체 서비스 포트폴리오 내 펀드 상세 조회
  portfolio-service/src/main/java/com/pda/portfolio_service/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/HititPortfoliosFundsStocksAndBondsResponseDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioFund.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioFundAsset.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioFundAssetRepository.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioFundBond.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioFundBondId.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioFundBondRepository.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioFundId.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioFundRepository.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioFundStock.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioFundStockId.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/PortfolioFundStockRepository.java
  portfolio-service/src/main/java/com/pda/portfolio_service/service/PortfolioService.java
Labels: ✨ feature

#41 #40 refactor: 자체 서비스 내 포트폴리오 조회 로직 수정
  portfolio-service/src/main/java/com/pda/portfolio_service/service/PortfolioService.java
Labels: ♻️ refactor

#53 #52 !HOTFIX: LoginDto에 기본 생성자 추가
  user-service/src/main/java/com/pda/user_service/dto/LoginDto.java
Labels: 🐛 bug/error

#58 #37 feat: 노후준비종합진단 API 추가
  user-service/src/main/java/com/pda/UserServiceApplication.java
  user-service/src/main/java/com/pda/investment_test/service/InvestmentTestService.java
  user-service/src/main/java/com/pda/retirements/controller/RetirementController.java
  user-service/src/main/java/com/pda/retirements/dto/RetirementTestRequestDto.java
  user-service/src/main/java/com/pda/retirements/dto/RetirementTestResponseDto.java
  user-service/src/main/java/com/pda/retirements/jpa/Gender.java
  user-service/src/main/java/com/pda/retirements/jpa/RetirementTestResult.java
  user-service/src/main/java/com/pda/retirements/jpa/RetirementTestResultRepository.java
  user-service/src/main/java/com/pda/retirements/jpa/RetirementType.java
  user-service/src/main/java/com/pda/retirements/service/RetirementService.java
  user-service/src/main/java/com/pda/user_service/service/UserService.java
  utils/src/main/java/com/pda/utils/api_utils/CustomNumberUtils.java
  utils/src/main/java/com/pda/utils/api_utils/CustomStringUtils.java
  utils/src/test/java/com/pda/utils/api_utils/CustomNumberUtilsTest.java
  utils/src/test/java/com/pda/utils/api_utils/CustomStringUtilsTest.java
Labels: ✨ feature

#62 #37 fix: RetirementTestRequestDto에 기본 생성자 추가
  user-service/src/main/java/com/pda/retirements/dto/RetirementTestRequestDto.java
Labels: 🐛 bug/error

#64 #37 fix: 노후종합진단 FE와 연동하며 수정
  user-service/src/main/java/com/pda/retirements/dto/RetirementTestResponseDto.java
  user-service/src/main/java/com/pda/retirements/jpa/RetirementTestResult.java
  user-service/src/main/java/com/pda/retirements/jpa/RetirementType.java
Labels: 🐛 bug/error, ✨ feature

#66 #59 chore: rabbitMQ 환경 설정 및 예제 구현
  .gitignore
  build.gradle
  portfolio-service/src/main/java/com/pda/portfolio_service/controller/PortfolioMessageController.java
  user-service/src/main/java/com/pda/security/WebSecurityConfig.java
  user-service/src/main/java/com/pda/user_service/service/UserMessageService.java
  utils/src/main/java/com/pda/utils/rabbitmq/config/RabbitMQConfig.java
  utils/src/main/java/com/pda/utils/rabbitmq/dto/AlarmDto.java
  utils/src/main/java/com/pda/utils/rabbitmq/service/MessageService.java
Labels: ✨ feature, ⚙️ chore

#71 #70 feat: 로그인 시 생년월일 반환
  user-service/src/main/java/com/pda/user_service/dto/UserInfoDto.java
Labels: ✨ feature

#73 #67 feat: 리밸런싱 알림 기능 추가
  asset-service/src/main/java/com/pda/asset_service/controller/AccountController.java
  portfolio-service/src/main/java/com/pda/portfolio_service/PortfolioServiceApplication.java
  portfolio-service/src/main/java/com/pda/portfolio_service/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolio_service/controller/PortfolioMessageController.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/FundProductDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/HititPortfoliosFundsStocksAndBondsResponseDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/MyDataFlaskLevelTest.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/MyDataPortfolioDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/OptimizeDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/OptimizeResponseCamelCaseDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/OptimizeResponseMapper.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/PortfolioFundAssetResponseDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/UserPortfolioFundRequestDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto_test/Bond.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto_test/Fund.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto_test/MyDataTestDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto_test/Portfolio.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto_test/PortfolioResponse.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto_test/Stock.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/FlaskTestServiceClient.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/MyDataFlaskLevelTestResponseDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/MyDataFlaskResponseDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/MyDataFundData.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/MyDataPortfolioServiceClient.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/MyDataTransaction.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/OptimizeResponseDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/OptimizeServiceClient.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/FundBonds.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/FundBondsRepository.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/FundProducts.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/FundProductsRepository.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/FundStocks.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/FundStocksRepository.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/UserPortfolio.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/UserPortfolioRepository.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/UserPortfolios.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/UserPortfoliosFundProducts.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/UserPortfoliosFundProductsRepository.java
  portfolio-service/src/main/java/com/pda/portfolio_service/jpa/UserPortfoliosRepository.java
  portfolio-service/src/main/java/com/pda/portfolio_service/service/PortfolioService.java
  portfolio-service/src/main/resources/application.properties
  user-service/src/main/java/com/pda/UserServiceApplication.java
  user-service/src/main/java/com/pda/notification/controller/NotificationController.java
  user-service/src/main/java/com/pda/notification/jpa/Notification.java
  user-service/src/main/java/com/pda/notification/jpa/NotificationRepository.java
  user-service/src/main/java/com/pda/notification/service/NotificationService.java
  user-service/src/main/java/com/pda/retirements/controller/RetirementController.java
  user-service/src/main/java/com/pda/user_service/service/UserMessageService.java
  utils/src/main/java/com/pda/utils/exception/GlobalExceptionHandler.java
  utils/src/main/java/com/pda/utils/rabbitmq/dto/NotificationDto.java
  utils/src/main/java/com/pda/utils/rabbitmq/service/MessageService.java
  utils/src/main/java/com/pda/utils/security/WebSecurityConfig.java
Labels: ✨ feature

#76 #75 chore: gitignore 수정
  .gitignore
  user-service/src/main/resources/application-mq.properties
  utils/src/main/resources/application-mq.properties
Labels: ⚙️ chore

#80 #67 feat: 알림 읽기 API 추가
  user-service/src/main/java/com/pda/notification/controller/NotificationController.java
  user-service/src/main/java/com/pda/notification/jpa/Notification.java
  user-service/src/main/java/com/pda/notification/service/NotificationService.java
Labels: ✨ feature

#81 #67 fix: 변경된 메서드명 반영
  user-service/src/main/java/com/pda/notification/controller/NotificationController.java
Labels: 🐛 bug/error

#79 #77 feat: user 나이, 투자 성향 테스트 점수 조회 API 추가 및 openFeign 추가
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/UserAgeTestScoreDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/UserServiceClient.java
  portfolio-service/src/main/java/com/pda/portfolio_service/service/PortfolioService.java
  user-service/src/main/java/com/pda/user_service/controller/UserController.java
  user-service/src/main/java/com/pda/user_service/controller/UserOpenFeignController.java
  user-service/src/main/java/com/pda/user_service/dto/UserAgeTestScoreDto.java
  utils/src/main/java/com/pda/utils/security/WebSecurityConfig.java
  utils/src/main/java/com/pda/utils/security/openfeign/AuthClient.java
Labels: ✨ feature

#82 #77 feat: portfolio-service에서 user-service, asset-service로 openfeign 요청 API 구현
  asset-service/src/main/java/com/pda/asset_service/controller/AssetController.java
  portfolio-service/src/main/java/com/pda/portfolio_service/PortfolioServiceApplication.java
  portfolio-service/src/main/java/com/pda/portfolio_service/controller/DataController.java
  portfolio-service/src/main/java/com/pda/portfolio_service/dto/UserAgeTestScoreDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/MydataAssetClient.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/MydataDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/MydataUserClient.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/PensionResponseDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/SecurityAccountStocksDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/SecurityAccountTransactionsDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/SecurityTransactionDto.java
  portfolio-service/src/main/java/com/pda/portfolio_service/feign/UserServiceClient.java
  portfolio-service/src/main/java/com/pda/portfolio_service/service/DataService.java
  portfolio-service/src/main/java/com/pda/portfolio_service/service/PortfolioService.java
  portfolio-service/src/main/resources/application.properties
  user-service/src/main/java/com/pda/user_service/controller/UserController.java
  user-service/src/main/java/com/pda/user_service/controller/UserOpenFeignController.java
  user-service/src/main/java/com/pda/user_service/dto/UserAgeTestScoreDto.java
  user-service/src/main/resources/application.properties
  utils/src/main/java/com/pda/utils/security/WebSecurityConfig.java
  utils/src/main/java/com/pda/utils/security/openfeign/AuthClient.java
Labels: ✨ feature

#84 #83 !HOTFIX: 주석 처리 해제
  user-service/src/main/java/com/pda/user_service/service/UserService.java
Labels: 🐛 bug/error

#85 fix: cors 설정에 PATCH 메서드 추가
  utils/src/main/java/com/pda/utils/security/WebSecurityConfig.java
Labels: 🐛 bug/error
